async def alldata():
    countries = [['Russia', 17098242, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ru.png'],
                 ['Canada', 9984670, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ca.png'],
                 ['China', 9706961, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/cn.png'],
                 ['United States', 9372610, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/us.png'],
                 ['Brazil', 8515767, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/br.png'],
                 ['Australia', 7692024, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/au.png'],
                 ['India', 3287590, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/in.png'],
                 ['Argentina', 2780400, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ar.png'],
                 ['Kazakhstan', 2724900, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/kz.png'],
                 ['Algeria', 2381741, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/dz.png'],
                 ['DR Congo', 2344858, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/cd.png'],
                 ['Greenland', 2166086, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/gl.png'],
                 ['Saudi Arabia', 2149690, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/sa.png'],
                 ['Mexico', 1964375, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/mx.png'],
                 ['Indonesia', 1904569, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/id.png'],
                 ['Sudan', 1886068, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/sd.png'],
                 ['Libya', 1759540, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ly.png'],
                 ['Iran', 1648195, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ir.png'],
                 ['Mongolia', 1564110, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/mn.png'],
                 ['Peru', 1285216, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/pe.png'],
                 ['Chad', 1284000, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/td.png'],
                 ['Niger', 1267000, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ne.png'],
                 ['Angola', 1246700, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ao.png'],
                 ['Mali', 1240192, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ml.png'],
                 ['South Africa', 1221037, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/za.png'],
                 ['Colombia', 1141748, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/co.png'],
                 ['Ethiopia', 1104300, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/et.png'],
                 ['Bolivia', 1098581, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/bo.png'],
                 ['Mauritania', 1030700, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/mr.png'],
                 ['Egypt', 1002450, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/eg.png'],
                 ['Tanzania', 945087, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/tz.png'],
                 ['Nigeria', 923768, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ng.png'],
                 ['Venezuela', 916445, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ve.png'],
                 ['Pakistan', 881912, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/pk.png'],
                 ['Namibia', 825615, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/na.png'],
                 ['Mozambique', 801590, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/mz.png'],
                 ['Turkey', 783562, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/tr.png'],
                 ['Chile', 756102, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/cl.png'],
                 ['Zambia', 752612, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/zm.png'],
                 ['Myanmar', 676578, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/mm.png'],
                 ['Afghanistan', 652230, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/af.png'],
                 ['Somalia', 637657, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/so.png'],
                 ['Central African Republic', 622984,
                  'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/cf.png'],
                 ['South Sudan', 619745, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ss.png'],
                 ['Ukraine', 603500, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ua.png'],
                 ['Madagascar', 587041, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/mg.png'],
                 ['Botswana', 582000, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/bw.png'],
                 ['Kenya', 580367, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ke.png'],
                 ['France', 551695, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/fr.png'],
                 ['Yemen', 527968, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ye.png'],
                 ['Thailand', 513120, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/th.png'],
                 ['Spain', 505992, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/es.png'],
                 ['Turkmenistan', 488100, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/tm.png'],
                 ['Cameroon', 475442, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/cm.png'],
                 ['Papua New Guinea', 462840, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/pg.png'],
                 ['Sweden', 450295, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/se.png'],
                 ['Uzbekistan', 488100, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/uz.png'],
                 ['Morocco', 446550, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ma.png'],
                 ['Iraq', 438317, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/iq.png'],
                 ['Paraguay', 406752, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/py.png'],
                 ['Zimbabwe', 390757, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/zw.png'],
                 ['Japan', 377930, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/jp.png'],
                 ['Germany', 357114, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/de.png'],
                 ['Philippines', 342353, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ph.png'],
                 ['Congo', 342000, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/cg.png'],
                 ['Finland', 338424, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/fi.png'],
                 ['Vietnam', 331212, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/vn.png'],
                 ['Malaysia', 330803, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/my.png'],
                 ['Norway', 323802, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/no.png'],
                 ['Côte d Ivoire', 322463, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ci.png'],
                 ['Poland', 312679, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/pl.png'],
                 ['Oman', 309500, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/om.png'],
                 ['Italy', 301336, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/it.png'],
                 ['Ecuador', 276841, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ec.png'],
                 ['Burkina Faso', 272967, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/bf.png'],
                 ['New Zealand', 270467, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/nz.png'],
                 ['Gabon', 267668, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ga.png'],
                 ['Western Sahara', 266000, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/eh.png'],
                 ['Guinea', 245857, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/gn.png'],
                 ['United Kingdom', 242900, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/gb.png'],
                 ['Uganda', 241550, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ug.png'],
                 ['Ghana', 238533, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/gh.png'],
                 ['Romania', 238391, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ro.png'],
                 ['Laos', 236800, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/la.png'],
                 ['Guyana', 214969, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/gy.png'],
                 ['Belarus', 207600, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/by.png'],
                 ['Kyrgyzstan', 199951, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/kg.png'],
                 ['Senegal', 196722, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/sn.png'],
                 ['Syria', 185180, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/sy.png'],
                 ['Cambodia', 181035, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/kh.png'],
                 ['Uruguay', 181034, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/uy.png'],
                 ['Suriname', 163820, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/sr.png'],
                 ['Tunisia', 163610, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/tn.png'],
                 ['Bangladesh', 147570, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/bd.png'],
                 ['Nepal', 147181, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/np.png'],
                 ['Tajikistan', 143100, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/tj.png'],
                 ['Greece', 131990, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/gr.png'],
                 ['Nicaragua', 130373, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ni.png'],
                 ['North Korea', 120538, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/kp.png'],
                 ['Malawi', 118484, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/mw.png'],
                 ['Eritrea', 117600, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/er.png'],
                 ['Benin', 112622, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/bj.png'],
                 ['Honduras', 112492, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/hn.png'],
                 ['Liberia', 111369, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/lr.png'],
                 ['Bulgaria', 110879, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/bg.png'],
                 ['Cuba', 109884, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/cu.png'],
                 ['Guatemala', 108889, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/gt.png'],
                 ['Iceland', 103000, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/is.png'],
                 ['South Korea', 100210, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/kr.png'],
                 ['Hungary', 93028, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/hu.png'],
                 ['Portugal', 92090, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/pt.png'],
                 ['Jordan', 89342, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/jo.png'],
                 ['Serbia', 88361, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/rs.png'],
                 ['Azerbaijan', 86600, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/az.png'],
                 ['Austria', 83871, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/at.png'],
                 ['United Arab Emirates', 83600,
                  'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ae.png'],
                 ['French Guiana', 83534, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/gf.png'],
                 ['Czechia', 78865, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/cz.png'],
                 ['Panama', 75417, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/pa.png'],
                 ['Sierra Leone', 71740, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/sl.png'],
                 ['Ireland', 70273, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ie.png'],
                 ['Georgia', 69700, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ge.png'],
                 ['Sri Lanka', 65610, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/lk.png'],
                 ['Lithuania', 65300, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/lt.png'],
                 ['Latvia', 64559, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/lv.png'],
                 ['Togo', 56785, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/tg.png'],
                 ['Croatia', 56594, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/hr.png'],
                 ['Bosnia and Herzegovina', 51209,
                  'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ba.png'],
                 ['Costa Rica', 51100, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/cr.png'],
                 ['Slovakia', 49037, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/sk.png'],
                 ['Dominican Republic', 48671,
                  'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/do.png'],
                 ['Estonia', 45227, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ee.png'],
                 ['Denmark', 43094, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/dk.png'],
                 ['Netherlands', 41850, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/nl.png'],
                 ['Switzerland', 41284, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ch.png'],
                 ['Bhutan', 38394, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/bt.png'],
                 ['Taiwan', 36193, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/tw.png'],
                 ['Guinea-Bissau', 36125, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/gw.png'],
                 ['Moldova', 33846, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/md.png'],
                 ['Belgium', 30528, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/be.png'],
                 ['Lesotho', 30355, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ls.png'],
                 ['Armenia', 29743, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/am.png'],
                 ['Solomon Islands', 28896, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/sb.png'],
                 ['Albania', 28748, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/al.png'],
                 ['Equatorial Guinea', 28051, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/gq.png'],
                 ['Burundi', 27834, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/bi.png'],
                 ['Haiti', 27750, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/ht.png'],
                 ['Rwanda', 26338, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/rw.png'],
                 ['Republic of North Macedonia', 25713,
                  'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/mk.png'],
                 ['Djibouti', 23200, 'https://raw.githubusercontent.com/hampusborgos/country-flags/main/png1000px/dj.png']]

    country_list = []
    for country in countries:
        country_list.append(country)

    return country_list


async def namedata(country):
    countries = await alldata()
    for i in countries:
        if i[0] == country:
            return i[0]

async def sizedata(country):
    countries = await alldata()
    for i in countries:
        if i[0] == country:
            return i[1]

async def flagdata(country):
    countries = await alldata()
    for i in countries:
        if i[0] == country:
            return i[2]

async def getiso(country):
    countries = [["Afghanistan", "AF"], ["Albania", "AL"], ["Algeria", "DZ"], ["American Samoa", "AS"],
                 ["Andorra", "AD"], ["Angola", "AO"], ["Anguilla", "AI"], ["Antarctica", "AQ"],
                 ["Antigua and Barbuda", "AG"], ["Argentina", "AR"], ["Armenia", "AM"], ["Aruba", "AW"],
                 ["Australia", "AU"], ["Austria", "AT"], ["Azerbaijan", "AZ"], ["Bahamas", "BS"], ["Bahrain", "BH"],
                 ["Bangladesh", "BD"], ["Barbados", "BB"], ["Belarus", "BY"], ["Belgium", "BE"], ["Belize", "BZ"],
                 ["Benin", "BJ"], ["Bermuda", "BM"], ["Bhutan", "BT"], ["Bolivia", "BO"],
                 ["Bosnia and Herzegovina", "BA"], ["Botswana", "BW"], ["Bouvet Island", "BV"], ["Brazil", "BR"],
                 ["British Indian Ocean Territory", "IO"], ["Brunei Darussalam", "BN"], ["Bulgaria", "BG"],
                 ["Burkina Faso", "BF"], ["Burundi", "BI"], ["Cambodia", "KH"], ["Cameroon", "CM"], ["Canada", "CA"],
                 ["Cape Verde", "CV"], ["Cayman Islands", "KY"], ["Central African Republic", "CF"], ["Chad", "TD"],
                 ["Chile", "CL"], ["China", "CN"], ["Christmas Island", "CX"], ["Cocos Islands", "CC"],
                 ["Colombia", "CO"], ["Comoros", "KM"], ["Congo", "CG"],
                 ["Congo", "CD"], ["Cook Islands", "CK"], ["Costa Rica", "CR"],
                 ["Cote D'Ivoire", "CI"], ["Croatia", "HR"], ["Cuba", "CU"], ["Cyprus", "CY"], ["Czech Republic", "CZ"],
                 ["Denmark", "DK"], ["Djibouti", "DJ"], ["Dominica", "DM"], ["Dominican Republic", "DO"],
                 ["Ecuador", "EC"], ["Egypt", "EG"], ["El Salvador", "SV"], ["Equatorial Guinea", "GQ"],
                 ["Eritrea", "ER"], ["Estonia", "EE"], ["Ethiopia", "ET"], ["Falkland Islands", "FK"],
                 ["Faroe Islands", "FO"], ["Fiji", "FJ"], ["Finland", "FI"], ["France", "FR"], ["French Guiana", "GF"],
                 ["French Polynesia", "PF"], ["French Southern Territories", "TF"], ["Gabon", "GA"], ["Gambia", "GM"],
                 ["Georgia", "GE"], ["Germany", "DE"], ["Ghana", "GH"], ["Gibraltar", "GI"], ["Greece", "GR"],
                 ["Greenland", "GL"], ["Grenada", "GD"], ["Guadeloupe", "GP"], ["Guam", "GU"], ["Guatemala", "GT"],
                 ["Guinea", "GN"], ["Guinea-Bissau", "GW"], ["Guyana", "GY"], ["Haiti", "HT"],
                 ["Heard Island and Mcdonald Islands", "HM"], ["Vatican City", "VA"],
                 ["Honduras", "HN"], ["Hong Kong", "HK"], ["Hungary", "HU"], ["Iceland", "IS"], ["India", "IN"],
                 ["Indonesia", "ID"], ["Iran", "IR"], ["Iraq", "IQ"], ["Ireland", "IE"],
                 ["Israel", "IL"], ["Italy", "IT"], ["Jamaica", "JM"], ["Japan", "JP"], ["Jordan", "JO"],
                 ["Kazakhstan", "KZ"], ["Kenya", "KE"], ["Kiribati", "KI"], ["Kuwait", "KW"],
                 ["Kyrgyzstan", "KG"], ["Lao People's Democratic Republic", "LA"], ["Latvia", "LV"], ["Lebanon", "LB"],
                 ["Lesotho", "LS"], ["Liberia", "LR"], ["Libyan Arab Jamahiriya", "LY"], ["Liechtenstein", "LI"],
                 ["Lithuania", "LT"], ["Luxembourg", "LU"], ["Macao", "MO"],
                 ["Macedonia", "MK"], ["Madagascar", "MG"], ["Malawi", "MW"],
                 ["Malaysia", "MY"], ["Maldives", "MV"], ["Mali", "ML"], ["Malta", "MT"], ["Marshall Islands", "MH"],
                 ["Martinique", "MQ"], ["Mauritania", "MR"], ["Mauritius", "MU"], ["Mayotte", "YT"], ["Mexico", "MX"],
                 ["Micronesia", "FM"], ["Moldova", "MD"], ["Monaco", "MC"],
                 ["Mongolia", "MN"], ["Montserrat", "MS"], ["Morocco", "MA"], ["Mozambique", "MZ"], ["Myanmar", "MM"],
                 ["Namibia", "NA"], ["Nauru", "NR"], ["Nepal", "NP"], ["Netherlands", "NL"],
                 ["Netherlands Antilles", "AN"], ["New Caledonia", "NC"], ["New Zealand", "NZ"], ["Nicaragua", "NI"],
                 ["Niger", "NE"], ["Nigeria", "NG"], ["Niue", "NU"], ["Norfolk Island", "NF"],
                 ["Northern Mariana Islands", "MP"], ["Norway", "NO"], ["Oman", "OM"], ["Pakistan", "PK"],
                 ["Palau", "PW"], ["Palestinian", "PS"], ["Panama", "PA"],
                 ["Papua New Guinea", "PG"], ["Paraguay", "PY"], ["Peru", "PE"], ["Philippines", "PH"],
                 ["Pitcairn", "PN"], ["Poland", "PL"], ["Portugal", "PT"], ["Puerto Rico", "PR"], ["Qatar", "QA"],
                 ["Reunion", "RE"], ["Romania", "RO"], ["Russian Federation", "RU"], ["Rwanda", "RW"],
                 ["Saint Helena", "SH"], ["Saint Kitts and Nevis", "KN"], ["Saint Lucia", "LC"],
                 ["Saint Pierre and Miquelon", "PM"], ["Saint Vincent and the Grenadines", "VC"], ["Samoa", "WS"],
                 ["San Marino", "SM"], ["Sao Tome and Principe", "ST"], ["Saudi Arabia", "SA"], ["Senegal", "SN"],
                 ["Serbia and Montenegro", "CS"], ["Seychelles", "SC"], ["Sierra Leone", "SL"], ["Singapore", "SG"],
                 ["Slovakia", "SK"], ["Slovenia", "SI"], ["Solomon Islands", "SB"], ["Somalia", "SO"],
                 ["South Africa", "ZA"], ["South Georgia and the South Sandwich Islands", "GS"], ["Spain", "ES"],
                 ["Sri Lanka", "LK"], ["Sudan", "SD"], ["Suriname", "SR"], ["Svalbard and Jan Mayen", "SJ"],
                 ["Swaziland", "SZ"], ["Sweden", "SE"], ["Switzerland", "CH"], ["Syrian Arab Republic", "SY"],
                 ["Taiwan", "TW"], ["Tajikistan", "TJ"], ["Tanzaniaf", "TZ"],
                 ["Thailand", "TH"], ["Timor-Leste", "TL"], ["Togo", "TG"], ["Tokelau", "TK"], ["Tonga", "TO"],
                 ["Trinidad and Tobago", "TT"], ["Tunisia", "TN"], ["Turkey", "TR"], ["Turkmenistan", "TM"],
                 ["Turks and Caicos Islands", "TC"], ["Tuvalu", "TV"], ["Uganda", "UG"], ["Ukraine", "UA"],
                 ["United Arab Emirates", "AE"], ["United Kingdom", "GB"], ["United States", "US"], ["Uruguay", "UY"],
                 ["Uzbekistan", "UZ"],
                 ["Vanuatu", "VU"], ["Venezuela", "VE"], ["Viet Nam", "VN"], ["Virgin Islands", "VG"],
                 ["Virgin Islands, U.s.", "VI"], ["Wallis and Futuna", "WF"], ["Western Sahara", "EH"], ["Yemen", "YE"],
                 ["Zambia", "ZM"], ["Zimbabwe", "ZW"], ]
    for i in countries:
        if i[0] == country:
            return i[1]

async def getcountryimage(country):
    countries = [["Afghanistan", "AF"], ["Albania", "AL"], ["Algeria", "DZ"], ["American Samoa", "AS"],
                 ["Andorra", "AD"], ["Angola", "AO"], ["Anguilla", "AI"], ["Antarctica", "AQ"],
                 ["Antigua and Barbuda", "AG"], ["Argentina", "AR"], ["Armenia", "AM"], ["Aruba", "AW"],
                 ["Australia", "AU"], ["Austria", "AT"], ["Azerbaijan", "AZ"], ["Bahamas", "BS"], ["Bahrain", "BH"],
                 ["Bangladesh", "BD"], ["Barbados", "BB"], ["Belarus", "BY"], ["Belgium", "BE"], ["Belize", "BZ"],
                 ["Benin", "BJ"], ["Bermuda", "BM"], ["Bhutan", "BT"], ["Bolivia", "BO"],
                 ["Bosnia and Herzegovina", "BA"], ["Botswana", "BW"], ["Bouvet Island", "BV"], ["Brazil", "BR"],
                 ["British Indian Ocean Territory", "IO"], ["Brunei Darussalam", "BN"], ["Bulgaria", "BG"],
                 ["Burkina Faso", "BF"], ["Burundi", "BI"], ["Cambodia", "KH"], ["Cameroon", "CM"], ["Canada", "CA"],
                 ["Cape Verde", "CV"], ["Cayman Islands", "KY"], ["Central African Republic", "CF"], ["Chad", "TD"],
                 ["Chile", "CL"], ["China", "CN"], ["Christmas Island", "CX"], ["Cocos Islands", "CC"],
                 ["Colombia", "CO"], ["Comoros", "KM"], ["Congo", "CG"],
                 ["Congo", "CD"], ["Cook Islands", "CK"], ["Costa Rica", "CR"],
                 ["Cote D'Ivoire", "CI"], ["Croatia", "HR"], ["Cuba", "CU"], ["Cyprus", "CY"], ["Czech Republic", "CZ"],
                 ["Denmark", "DK"], ["Djibouti", "DJ"], ["Dominica", "DM"], ["Dominican Republic", "DO"],
                 ["Ecuador", "EC"], ["Egypt", "EG"], ["El Salvador", "SV"], ["Equatorial Guinea", "GQ"],
                 ["Eritrea", "ER"], ["Estonia", "EE"], ["Ethiopia", "ET"], ["Falkland Islands", "FK"],
                 ["Faroe Islands", "FO"], ["Fiji", "FJ"], ["Finland", "FI"], ["France", "FR"], ["French Guiana", "GF"],
                 ["French Polynesia", "PF"], ["French Southern Territories", "TF"], ["Gabon", "GA"], ["Gambia", "GM"],
                 ["Georgia", "GE"], ["Germany", "DE"], ["Ghana", "GH"], ["Gibraltar", "GI"], ["Greece", "GR"],
                 ["Greenland", "GL"], ["Grenada", "GD"], ["Guadeloupe", "GP"], ["Guam", "GU"], ["Guatemala", "GT"],
                 ["Guinea", "GN"], ["Guinea-Bissau", "GW"], ["Guyana", "GY"], ["Haiti", "HT"],
                 ["Heard Island and Mcdonald Islands", "HM"], ["Vatican City", "VA"],
                 ["Honduras", "HN"], ["Hong Kong", "HK"], ["Hungary", "HU"], ["Iceland", "IS"], ["India", "IN"],
                 ["Indonesia", "ID"], ["Iran", "IR"], ["Iraq", "IQ"], ["Ireland", "IE"],
                 ["Israel", "IL"], ["Italy", "IT"], ["Jamaica", "JM"], ["Japan", "JP"], ["Jordan", "JO"],
                 ["Kazakhstan", "KZ"], ["Kenya", "KE"], ["Kiribati", "KI"], ["Kuwait", "KW"],
                 ["Kyrgyzstan", "KG"], ["Lao People's Democratic Republic", "LA"], ["Latvia", "LV"], ["Lebanon", "LB"],
                 ["Lesotho", "LS"], ["Liberia", "LR"], ["Libyan Arab Jamahiriya", "LY"], ["Liechtenstein", "LI"],
                 ["Lithuania", "LT"], ["Luxembourg", "LU"], ["Macao", "MO"],
                 ["Macedonia", "MK"], ["Madagascar", "MG"], ["Malawi", "MW"],
                 ["Malaysia", "MY"], ["Maldives", "MV"], ["Mali", "ML"], ["Malta", "MT"], ["Marshall Islands", "MH"],
                 ["Martinique", "MQ"], ["Mauritania", "MR"], ["Mauritius", "MU"], ["Mayotte", "YT"], ["Mexico", "MX"],
                 ["Micronesia", "FM"], ["Moldova", "MD"], ["Monaco", "MC"],
                 ["Mongolia", "MN"], ["Montserrat", "MS"], ["Morocco", "MA"], ["Mozambique", "MZ"], ["Myanmar", "MM"],
                 ["Namibia", "NA"], ["Nauru", "NR"], ["Nepal", "NP"], ["Netherlands", "NL"],
                 ["Netherlands Antilles", "AN"], ["New Caledonia", "NC"], ["New Zealand", "NZ"], ["Nicaragua", "NI"],
                 ["Niger", "NE"], ["Nigeria", "NG"], ["Niue", "NU"], ["Norfolk Island", "NF"],
                 ["Northern Mariana Islands", "MP"], ["Norway", "NO"], ["Oman", "OM"], ["Pakistan", "PK"],
                 ["Palau", "PW"], ["Palestinian", "PS"], ["Panama", "PA"],
                 ["Papua New Guinea", "PG"], ["Paraguay", "PY"], ["Peru", "PE"], ["Philippines", "PH"],
                 ["Pitcairn", "PN"], ["Poland", "PL"], ["Portugal", "PT"], ["Puerto Rico", "PR"], ["Qatar", "QA"],
                 ["Reunion", "RE"], ["Romania", "RO"], ["Russian Federation", "RU"], ["Rwanda", "RW"],
                 ["Saint Helena", "SH"], ["Saint Kitts and Nevis", "KN"], ["Saint Lucia", "LC"],
                 ["Saint Pierre and Miquelon", "PM"], ["Saint Vincent and the Grenadines", "VC"], ["Samoa", "WS"],
                 ["San Marino", "SM"], ["Sao Tome and Principe", "ST"], ["Saudi Arabia", "SA"], ["Senegal", "SN"],
                 ["Serbia and Montenegro", "CS"], ["Seychelles", "SC"], ["Sierra Leone", "SL"], ["Singapore", "SG"],
                 ["Slovakia", "SK"], ["Slovenia", "SI"], ["Solomon Islands", "SB"], ["Somalia", "SO"],
                 ["South Africa", "ZA"], ["South Georgia and the South Sandwich Islands", "GS"], ["Spain", "ES"],
                 ["Sri Lanka", "LK"], ["Sudan", "SD"], ["Suriname", "SR"], ["Svalbard and Jan Mayen", "SJ"],
                 ["Swaziland", "SZ"], ["Sweden", "SE"], ["Switzerland", "CH"], ["Syrian Arab Republic", "SY"],
                 ["Taiwan", "TW"], ["Tajikistan", "TJ"], ["Tanzaniaf", "TZ"],
                 ["Thailand", "TH"], ["Timor-Leste", "TL"], ["Togo", "TG"], ["Tokelau", "TK"], ["Tonga", "TO"],
                 ["Trinidad and Tobago", "TT"], ["Tunisia", "TN"], ["Turkey", "TR"], ["Turkmenistan", "TM"],
                 ["Turks and Caicos Islands", "TC"], ["Tuvalu", "TV"], ["Uganda", "UG"], ["Ukraine", "UA"],
                 ["United Arab Emirates", "AE"], ["United Kingdom", "GB"], ["United States", "US"], ["Uruguay", "UY"],
                 ["Uzbekistan", "UZ"],
                 ["Vanuatu", "VU"], ["Venezuela", "VE"], ["Viet Nam", "VN"], ["Virgin Islands", "VG"],
                 ["Virgin Islands, U.s.", "VI"], ["Wallis and Futuna", "WF"], ["Western Sahara", "EH"], ["Yemen", "YE"],
                 ["Zambia", "ZM"], ["Zimbabwe", "ZW"], ]
    for i in countries:
        if i[0] == country:
            iso = i[1]
            return f"https://raw.githubusercontent.com/djaiss/mapsicon/master/all/{iso.lower()}/1024.png"

async def allisocountries():
    countries = [["Afghanistan", "AF"], ["Albania", "AL"], ["Algeria", "DZ"], ["American Samoa", "AS"],
                 ["Andorra", "AD"], ["Angola", "AO"], ["Anguilla", "AI"], ["Antarctica", "AQ"],
                 ["Antigua and Barbuda", "AG"], ["Argentina", "AR"], ["Armenia", "AM"], ["Aruba", "AW"],
                 ["Australia", "AU"], ["Austria", "AT"], ["Azerbaijan", "AZ"], ["Bahamas", "BS"], ["Bahrain", "BH"],
                 ["Bangladesh", "BD"], ["Barbados", "BB"], ["Belarus", "BY"], ["Belgium", "BE"], ["Belize", "BZ"],
                 ["Benin", "BJ"], ["Bermuda", "BM"], ["Bhutan", "BT"], ["Bolivia", "BO"],
                 ["Bosnia and Herzegovina", "BA"], ["Botswana", "BW"], ["Bouvet Island", "BV"], ["Brazil", "BR"],
                 ["British Indian Ocean Territory", "IO"], ["Brunei Darussalam", "BN"], ["Bulgaria", "BG"],
                 ["Burkina Faso", "BF"], ["Burundi", "BI"], ["Cambodia", "KH"], ["Cameroon", "CM"], ["Canada", "CA"],
                 ["Cape Verde", "CV"], ["Cayman Islands", "KY"], ["Central African Republic", "CF"], ["Chad", "TD"],
                 ["Chile", "CL"], ["China", "CN"], ["Christmas Island", "CX"], ["Cocos Islands", "CC"],
                 ["Colombia", "CO"], ["Comoros", "KM"], ["Congo", "CG"],
                 ["Congo", "CD"], ["Cook Islands", "CK"], ["Costa Rica", "CR"],
                 ["Cote D'Ivoire", "CI"], ["Croatia", "HR"], ["Cuba", "CU"], ["Cyprus", "CY"], ["Czech Republic", "CZ"],
                 ["Denmark", "DK"], ["Djibouti", "DJ"], ["Dominica", "DM"], ["Dominican Republic", "DO"],
                 ["Ecuador", "EC"], ["Egypt", "EG"], ["El Salvador", "SV"], ["Equatorial Guinea", "GQ"],
                 ["Eritrea", "ER"], ["Estonia", "EE"], ["Ethiopia", "ET"], ["Falkland Islands", "FK"],
                 ["Faroe Islands", "FO"], ["Fiji", "FJ"], ["Finland", "FI"], ["France", "FR"], ["French Guiana", "GF"],
                 ["French Polynesia", "PF"], ["French Southern Territories", "TF"], ["Gabon", "GA"], ["Gambia", "GM"],
                 ["Georgia", "GE"], ["Germany", "DE"], ["Ghana", "GH"], ["Gibraltar", "GI"], ["Greece", "GR"],
                 ["Greenland", "GL"], ["Grenada", "GD"], ["Guadeloupe", "GP"], ["Guam", "GU"], ["Guatemala", "GT"],
                 ["Guinea", "GN"], ["Guinea-Bissau", "GW"], ["Guyana", "GY"], ["Haiti", "HT"],
                 ["Heard Island and Mcdonald Islands", "HM"], ["Vatican City", "VA"],
                 ["Honduras", "HN"], ["Hong Kong", "HK"], ["Hungary", "HU"], ["Iceland", "IS"], ["India", "IN"],
                 ["Indonesia", "ID"], ["Iran", "IR"], ["Iraq", "IQ"], ["Ireland", "IE"],
                 ["Israel", "IL"], ["Italy", "IT"], ["Jamaica", "JM"], ["Japan", "JP"], ["Jordan", "JO"],
                 ["Kazakhstan", "KZ"], ["Kenya", "KE"], ["Kiribati", "KI"], ["Kuwait", "KW"],
                 ["Kyrgyzstan", "KG"], ["Lao People's Democratic Republic", "LA"], ["Latvia", "LV"], ["Lebanon", "LB"],
                 ["Lesotho", "LS"], ["Liberia", "LR"], ["Libyan Arab Jamahiriya", "LY"], ["Liechtenstein", "LI"],
                 ["Lithuania", "LT"], ["Luxembourg", "LU"], ["Macao", "MO"],
                 ["Macedonia", "MK"], ["Madagascar", "MG"], ["Malawi", "MW"],
                 ["Malaysia", "MY"], ["Maldives", "MV"], ["Mali", "ML"], ["Malta", "MT"], ["Marshall Islands", "MH"],
                 ["Martinique", "MQ"], ["Mauritania", "MR"], ["Mauritius", "MU"], ["Mayotte", "YT"], ["Mexico", "MX"],
                 ["Micronesia", "FM"], ["Moldova", "MD"], ["Monaco", "MC"],
                 ["Mongolia", "MN"], ["Montserrat", "MS"], ["Morocco", "MA"], ["Mozambique", "MZ"], ["Myanmar", "MM"],
                 ["Namibia", "NA"], ["Nauru", "NR"], ["Nepal", "NP"], ["Netherlands", "NL"],
                 ["Netherlands Antilles", "AN"], ["New Caledonia", "NC"], ["New Zealand", "NZ"], ["Nicaragua", "NI"],
                 ["Niger", "NE"], ["Nigeria", "NG"], ["Niue", "NU"], ["Norfolk Island", "NF"],
                 ["Northern Mariana Islands", "MP"], ["Norway", "NO"], ["Oman", "OM"], ["Pakistan", "PK"],
                 ["Palau", "PW"], ["Palestinian", "PS"], ["Panama", "PA"],
                 ["Papua New Guinea", "PG"], ["Paraguay", "PY"], ["Peru", "PE"], ["Philippines", "PH"],
                 ["Pitcairn", "PN"], ["Poland", "PL"], ["Portugal", "PT"], ["Puerto Rico", "PR"], ["Qatar", "QA"],
                 ["Reunion", "RE"], ["Romania", "RO"], ["Russian Federation", "RU"], ["Rwanda", "RW"],
                 ["Saint Helena", "SH"], ["Saint Kitts and Nevis", "KN"], ["Saint Lucia", "LC"],
                 ["Saint Pierre and Miquelon", "PM"], ["Saint Vincent and the Grenadines", "VC"], ["Samoa", "WS"],
                 ["San Marino", "SM"], ["Sao Tome and Principe", "ST"], ["Saudi Arabia", "SA"], ["Senegal", "SN"],
                 ["Serbia and Montenegro", "CS"], ["Seychelles", "SC"], ["Sierra Leone", "SL"], ["Singapore", "SG"],
                 ["Slovakia", "SK"], ["Slovenia", "SI"], ["Solomon Islands", "SB"], ["Somalia", "SO"],
                 ["South Africa", "ZA"], ["South Georgia and the South Sandwich Islands", "GS"], ["Spain", "ES"],
                 ["Sri Lanka", "LK"], ["Sudan", "SD"], ["Suriname", "SR"], ["Svalbard and Jan Mayen", "SJ"],
                 ["Swaziland", "SZ"], ["Sweden", "SE"], ["Switzerland", "CH"], ["Syrian Arab Republic", "SY"],
                 ["Taiwan", "TW"], ["Tajikistan", "TJ"], ["Tanzaniaf", "TZ"],
                 ["Thailand", "TH"], ["Timor-Leste", "TL"], ["Togo", "TG"], ["Tokelau", "TK"], ["Tonga", "TO"],
                 ["Trinidad and Tobago", "TT"], ["Tunisia", "TN"], ["Turkey", "TR"], ["Turkmenistan", "TM"],
                 ["Turks and Caicos Islands", "TC"], ["Tuvalu", "TV"], ["Uganda", "UG"], ["Ukraine", "UA"],
                 ["United Arab Emirates", "AE"], ["United Kingdom", "GB"], ["United States", "US"], ["Uruguay", "UY"], ["Uzbekistan", "UZ"],
                 ["Vanuatu", "VU"], ["Venezuela", "VE"], ["Viet Nam", "VN"], ["Virgin Islands", "VG"],
                 ["Virgin Islands, U.s.", "VI"], ["Wallis and Futuna", "WF"], ["Western Sahara", "EH"], ["Yemen", "YE"],
                 ["Zambia", "ZM"], ["Zimbabwe", "ZW"], ]

    country_list = []
    for country in countries:
        country_list.append(country)

    return country_list
